# Generated by Django 4.2.7 on 2025-10-16 09:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام مکان')),
                ('facility_type', models.CharField(choices=[('pool', 'استخر'), ('gym', 'باشگاه ورزشی'), ('roof_garden', 'روف گاردن'), ('meeting_room', 'سالن اجتماعات'), ('party_hall', 'سالن جشن'), ('guest_parking', 'پارکینگ مهمان'), ('playground', 'زمین بازی'), ('sports_court', 'زمین ورزشی'), ('library', 'کتابخانه'), ('business_center', 'مرکز کسب و کار'), ('other', 'سایر')], max_length=20, verbose_name='نوع مکان')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('capacity', models.PositiveIntegerField(verbose_name='ظرفیت')),
                ('min_advance_booking', models.PositiveIntegerField(default=1, verbose_name='حداقل زمان رزرو قبلی (ساعت)')),
                ('max_advance_booking', models.PositiveIntegerField(default=168, verbose_name='حداکثر زمان رزرو قبلی (ساعت)')),
                ('opening_time', models.TimeField(verbose_name='ساعت شروع')),
                ('closing_time', models.TimeField(verbose_name='ساعت پایان')),
                ('rules', models.TextField(blank=True, null=True, verbose_name='قوانین استفاده')),
                ('hourly_rate', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه ساعتی')),
                ('is_free', models.BooleanField(default=True, verbose_name='رایگان')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('under_maintenance', models.BooleanField(default=False, verbose_name='در دست تعمیر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='complexes.complex', verbose_name='مجتمع')),
            ],
            options={
                'verbose_name': 'امکان عمومی',
                'verbose_name_plural': 'امکانات عمومی',
                'ordering': ['complex', 'facility_type'],
            },
        ),
        migrations.CreateModel(
            name='FacilityUsageRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.TextField(verbose_name='قانون')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='الزامی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_rules', to='facilities.facility', verbose_name='امکان')),
            ],
            options={
                'verbose_name': 'قانون استفاده',
                'verbose_name_plural': 'قوانین استفاده',
            },
        ),
        migrations.CreateModel(
            name='FacilityMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('maintenance_type', models.CharField(choices=[('routine', 'روتین'), ('repair', 'تعمیر'), ('cleaning', 'نظافت'), ('inspection', 'بازرسی'), ('upgrade', 'ارتقا')], max_length=20, verbose_name='نوع نگهداری')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('scheduled_start', models.DateTimeField(verbose_name='زمان شروع برنامه\u200cریزی شده')),
                ('scheduled_end', models.DateTimeField(verbose_name='زمان پایان برنامه\u200cریزی شده')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع واقعی')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان واقعی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('active', 'در حال استفاده'), ('completed', 'پایان یافته'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('affect_bookings', models.BooleanField(default=True, verbose_name='تأثیر بر رزروها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_facility_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_facility_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='facilities.facility', verbose_name='امکان')),
            ],
            options={
                'verbose_name': 'نگهداری امکان',
                'verbose_name_plural': 'نگهداری امکانات',
                'ordering': ['-scheduled_start'],
            },
        ),
        migrations.CreateModel(
            name='FacilityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='facility_images/', verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('is_primary', models.BooleanField(default=False, verbose_name='تصویر اصلی')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='facilities.facility', verbose_name='امکان')),
            ],
            options={
                'verbose_name': 'تصویر امکان',
                'verbose_name_plural': 'تصاویر امکانات',
            },
        ),
        migrations.CreateModel(
            name='FacilityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='زمان شروع')),
                ('end_time', models.DateTimeField(verbose_name='زمان پایان')),
                ('duration_hours', models.PositiveIntegerField(verbose_name='مدت زمان (ساعت)')),
                ('purpose', models.CharField(max_length=200, verbose_name='هدف استفاده')),
                ('participants_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='تعداد شرکت\u200cکنندگان')),
                ('special_requirements', models.TextField(blank=True, null=True, verbose_name='نیازهای ویژه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار تأیید'), ('confirmed', 'تأیید شده'), ('active', 'در حال استفاده'), ('completed', 'پایان یافته'), ('cancelled', 'لغو شده'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='هزینه کل')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['manager', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_bookings', to=settings.AUTH_USER_MODEL, verbose_name='تأیید کننده')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='facilities.facility', verbose_name='امکان')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_bookings', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'رزرو امکان',
                'verbose_name_plural': 'رزرو امکانات',
                'ordering': ['-start_time'],
            },
        ),
    ]
