# Generated by Django 5.2.7 on 2025-12-19 19:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0002_feature_building_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام هزینه')),
                ('charge_type', models.CharField(choices=[('monthly', 'شارژ ماهیانه'), ('building_maintenance', 'هزینه نگهداری ساختمان'), ('elevator', 'آسانسور'), ('cleaner', 'نظافت'), ('security', 'حفاظت'), ('green_space', 'فضای سبز'), ('pool', 'استخر'), ('gym', 'باشگاه'), ('other', 'سایر')], max_length=50, verbose_name='نوع هزینه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charge_templates', to='complexes.building', verbose_name='مجتمع')),
            ],
            options={
                'verbose_name': 'الگوی شارژ',
                'verbose_name_plural': 'الگوهای شارژ',
                'unique_together': {('complex', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='دوره')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('overdue', 'معوقه'), ('cancelled', 'لغو شده'), ('partially_paid', 'پرداخت جزئی')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پرداخت شده')),
                ('remaining_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ باقیمانده')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='complexes.unit', verbose_name='واحد')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financial.chargetemplate', verbose_name='الگوی شارژ')),
            ],
            options={
                'verbose_name': 'شارژ',
                'verbose_name_plural': 'شارژها',
                'ordering': ['-due_date', 'unit'],
                'unique_together': {('unit', 'template', 'period')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ تراکنش')),
                ('payment_method', models.CharField(choices=[('online', 'آنلاین'), ('cash', 'نقدی'), ('bank_transfer', 'کارت به کارت'), ('cheque', 'چک'), ('pos', 'دستگاه پوز')], max_length=20, verbose_name='روش پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده'), ('failed', 'ناموفق'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت تراکنش')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='شماره پیگیری')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.charge', verbose_name='شارژ مربوطه')),
            ],
            options={
                'verbose_name': 'تراکنش',
                'verbose_name_plural': 'تراکنش\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='دوره')),
                ('total_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ پرداخت شده')),
                ('remaining_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ باقیمانده')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده')),
                ('due_date', models.DateField(verbose_name='تاریخ سررسید')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='complexes.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-period', 'unit'],
                'unique_together': {('unit', 'period')},
            },
        ),
    ]
