# Generated by Django 4.2.7 on 2025-10-16 09:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان وظیفه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('assigned', 'تخصیص داده شده'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده'), ('on_hold', 'متوقف شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('due_date', models.DateTimeField(verbose_name='تاریخ سررسید')),
                ('estimated_hours', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='زمان تخمینی (ساعت)')),
                ('actual_hours', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)], verbose_name='زمان واقعی (ساعت)')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تخصیص')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('related_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='complexes.unit', verbose_name='واحد مربوطه')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['-due_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام تیم')),
                ('team_type', models.CharField(choices=[('security', 'حفاظت'), ('maintenance', 'تاسیسات'), ('cleaning', 'نظافت'), ('landscaping', 'فضای سبز'), ('pool', 'استخر'), ('gym', 'باشگاه'), ('other', 'سایر')], max_length=20, verbose_name='نوع تیم')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='complexes.complex', verbose_name='مجتمع')),
                ('members', models.ManyToManyField(blank=True, limit_choices_to={'user_type': 'staff'}, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
                ('supervisor', models.ForeignKey(limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_teams', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم\u200cها',
                'ordering': ['complex', 'team_type'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='نظر')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='task_attachments/', verbose_name='فایل ضمیمه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='operations.task', verbose_name='وظیفه')),
            ],
            options={
                'verbose_name': 'نظر وظیفه',
                'verbose_name_plural': 'نظرات وظایف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='operations.team', verbose_name='تیم'),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان درخواست')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('request_type', models.CharField(choices=[('maintenance', 'تعمیرات'), ('cleaning', 'نظافت'), ('security', 'امنیتی'), ('complaint', 'شکایت'), ('suggestion', 'پیشنهاد'), ('other', 'سایر')], max_length=20, verbose_name='نوع درخواست')),
                ('status', models.CharField(choices=[('submitted', 'ثبت شده'), ('under_review', 'در دست بررسی'), ('assigned', 'تخصیص داده شده'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='submitted', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تخصیص')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('assigned_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.team', verbose_name='تیم مسئول')),
                ('related_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_request', to='operations.task', verbose_name='وظیفه مرتبط')),
                ('submitted_by', models.ForeignKey(limit_choices_to={'user_type__in': ['resident', 'owner']}, on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='complexes.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'درخواست خدمات',
                'verbose_name_plural': 'درخواست\u200cهای خدمات',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=7, verbose_name='دوره')),
                ('total_tasks', models.PositiveIntegerField(default=0, verbose_name='تعداد کل وظایف')),
                ('completed_tasks', models.PositiveIntegerField(default=0, verbose_name='وظایف انجام شده')),
                ('overdue_tasks', models.PositiveIntegerField(default=0, verbose_name='وظایف معوقه')),
                ('average_completion_time', models.FloatField(default=0, verbose_name='میانگین زمان تکمیل (ساعت)')),
                ('satisfaction_rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نرخ رضایت (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='operations.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'عملکرد تیم',
                'verbose_name_plural': 'عملکرد تیم\u200cها',
                'ordering': ['-period', 'team'],
                'unique_together': {('team', 'period')},
            },
        ),
    ]
