# Generated by Django 5.2.7 on 2025-12-19 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complexes', '0002_feature_building_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('meeting_type', models.CharField(choices=[('board', 'Board'), ('general', 'General'), ('committee', 'Committee'), ('emergency', 'Emergency')], max_length=20, verbose_name='Meeting type')),
                ('description', models.TextField(verbose_name='Description')),
                ('agenda', models.TextField(verbose_name='Agenda')),
                ('scheduled_date', models.DateTimeField(verbose_name='Scheduled date')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Duration (minutes)')),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.building', verbose_name='Complex')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('attended', 'Attended'), ('absent', 'Absent')], default='invited', max_length=20, verbose_name='Attendance status')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Responded at')),
                ('actual_attendance', models.BooleanField(blank=True, null=True, verbose_name='Physical attendance')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.meeting', verbose_name='Meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Meeting attendance',
                'verbose_name_plural': 'Meeting attendances',
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings_attended', through='communications.MeetingAttendance', to=settings.AUTH_USER_MODEL, verbose_name='Attendees'),
        ),
        migrations.CreateModel(
            name='MeetingMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('decisions', models.TextField(verbose_name='Decisions')),
                ('action_items', models.TextField(verbose_name='Action items')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Recorded by')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='communications.meeting', verbose_name='Meeting')),
                ('signed_by', models.ManyToManyField(related_name='signed_minutes', to=settings.AUTH_USER_MODEL, verbose_name='Signatories')),
            ],
            options={
                'verbose_name': 'Meeting minute',
                'verbose_name_plural': 'Meeting minutes',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Name')),
                ('members', models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Members')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ticket title')),
                ('description', models.TextField(verbose_name='Description')),
                ('ticket_type', models.CharField(choices=[('technical', 'Technical'), ('financial', 'Financial'), ('complaint', 'Complaint'), ('suggestion', 'Suggestion'), ('general', 'General')], max_length=20, verbose_name='Ticket type')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20, verbose_name='Priority')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted at')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Assigned at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved at')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Closed at')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['manager', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Assigned to')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Submitted by')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.unit', verbose_name='Unit')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='communications.team', verbose_name='Team/Department')),
            ],
            options={
                'verbose_name': 'Support ticket',
                'verbose_name_plural': 'Support tickets',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('message', models.TextField(verbose_name='Message')),
                ('notification_type', models.CharField(choices=[('charge', 'Charge'), ('meeting', 'Meeting'), ('maintenance', 'Maintenance'), ('security', 'Security'), ('general', 'General'), ('urgent', 'Urgent')], max_length=20, verbose_name='Notification type')),
                ('target_type', models.CharField(choices=[('all', 'All residents'), ('owners', 'Owners'), ('residents', 'Residents'), ('board', 'Board'), ('specific', 'Specific users')], max_length=20, verbose_name='Recipients')),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is sent')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Scheduled at')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.building', verbose_name='Complex')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('specific_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Specific users')),
                ('target_teams', models.ManyToManyField(blank=True, to='communications.team', verbose_name='Target teams')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='target_teams',
            field=models.ManyToManyField(blank=True, to='communications.team', verbose_name='تیم\u200cهای هدف'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('content', models.TextField(verbose_name='Content')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20, verbose_name='Priority')),
                ('target_roles', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=False, verbose_name='Is published')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='Publish date')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='Expiry date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.building', verbose_name='Complex')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Created by')),
                ('target_units', models.ManyToManyField(blank=True, to='complexes.unit', verbose_name='Target units')),
                ('target_teams', models.ManyToManyField(blank=True, to='communications.team', verbose_name='Target teams')),
            ],
            options={
                'verbose_name': 'Announcement',
                'verbose_name_plural': 'Announcements',
                'ordering': ['-publish_date', '-priority'],
            },
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Message')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_attachments/', verbose_name='Attachment')),
                ('is_internal', models.BooleanField(default=False, verbose_name='Internal response')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Responder')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='communications.supportticket', verbose_name='Ticket')),
            ],
            options={
                'verbose_name': 'Ticket response',
                'verbose_name_plural': 'Ticket responses',
                'ordering': ['created_at'],
            },
        ),
    ]
