# Generated by Django 4.2.7 on 2025-10-16 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان جلسه')),
                ('meeting_type', models.CharField(choices=[('board', 'هیئت مدیره'), ('general', 'عمومی'), ('committee', 'کمیته'), ('emergency', 'فوری')], max_length=20, verbose_name='نوع جلسه')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('agenda', models.TextField(verbose_name='دستور جلسه')),
                ('scheduled_date', models.DateTimeField(verbose_name='زمان برگزاری')),
                ('location', models.CharField(max_length=200, verbose_name='محل برگزاری')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='مدت زمان (دقیقه)')),
                ('status', models.CharField(choices=[('scheduled', 'برنامه\u200cریزی شده'), ('ongoing', 'در حال برگزاری'), ('completed', 'برگزار شده'), ('cancelled', 'لغو شده')], default='scheduled', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان تیکت')),
                ('description', models.TextField(verbose_name='شرح مشکل')),
                ('ticket_type', models.CharField(choices=[('technical', 'فنی'), ('financial', 'مالی'), ('complaint', 'شکایت'), ('suggestion', 'پیشنهاد'), ('general', 'عمومی')], max_length=20, verbose_name='نوع تیکت')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در دست بررسی'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تخصیص')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان حل')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته شدن')),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['manager', 'staff']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='واگذار شده به')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'تیکت پشتیبانی',
                'verbose_name_plural': 'تیکت\u200cهای پشتیبانی',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='پیام')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_attachments/', verbose_name='فایل ضمیمه')),
                ('is_internal', models.BooleanField(default=False, verbose_name='پاسخ داخلی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='پاسخ دهنده')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='communications.supportticket', verbose_name='تیکت')),
            ],
            options={
                'verbose_name': 'پاسخ تیکت',
                'verbose_name_plural': 'پاسخ\u200cهای تیکت',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('notification_type', models.CharField(choices=[('charge', 'شارژ'), ('meeting', 'جلسه'), ('maintenance', 'تعمیرات'), ('security', 'امنیتی'), ('general', 'عمومی'), ('urgent', 'فوری')], max_length=20, verbose_name='نوع اطلاع\u200cرسانی')),
                ('target_type', models.CharField(choices=[('all', 'همه ساکنین'), ('owners', 'مالکین'), ('residents', 'ساکنین'), ('board', 'هیئت مدیره'), ('specific', 'کاربران خاص')], max_length=20, verbose_name='مخاطبان')),
                ('is_sent', models.BooleanField(default=False, verbose_name='ارسال شده')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان ارسال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.complex', verbose_name='مجتمع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_notifications', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('specific_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران خاص')),
            ],
            options={
                'verbose_name': 'اطلاع\u200cرسانی',
                'verbose_name_plural': 'اطلاع\u200cرسانی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingMinute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='متن صورتجلسه')),
                ('decisions', models.TextField(verbose_name='مصوبات')),
                ('action_items', models.TextField(verbose_name='اقدامات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('meeting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='minutes', to='communications.meeting', verbose_name='جلسه')),
                ('signed_by', models.ManyToManyField(related_name='signed_minutes', to=settings.AUTH_USER_MODEL, verbose_name='امضا کنندگان')),
            ],
            options={
                'verbose_name': 'صورتجلسه',
                'verbose_name_plural': 'صورتجلسات',
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'دعوت شده'), ('confirmed', 'تأیید حضور'), ('declined', 'عدم حضور'), ('attended', 'حاضر شده'), ('absent', 'غایب')], default='invited', max_length=20, verbose_name='وضعیت حضور')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پاسخ')),
                ('actual_attendance', models.BooleanField(blank=True, null=True, verbose_name='حضور فیزیکی')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='communications.meeting', verbose_name='جلسه')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حضور در جلسه',
                'verbose_name_plural': 'حضور در جلسات',
                'unique_together': {('meeting', 'user')},
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='attendees',
            field=models.ManyToManyField(related_name='meetings_attended', through='communications.MeetingAttendance', to=settings.AUTH_USER_MODEL, verbose_name='شرکت\u200cکنندگان'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='complex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.complex', verbose_name='مجتمع'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_meetings', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان اطلاعیه')),
                ('content', models.TextField(verbose_name='محتوا')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'معمولی'), ('high', 'بالا'), ('urgent', 'فوری')], default='normal', max_length=20, verbose_name='اولویت')),
                ('is_published', models.BooleanField(default=False, verbose_name='منتشر شده')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('expiry_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complexes.complex', verbose_name='مجتمع')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('target_units', models.ManyToManyField(blank=True, to='complexes.unit', verbose_name='واحدهای هدف')),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-publish_date', '-priority'],
            },
        ),
    ]
