# Generated by Django 5.2.7 on 2025-11-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('manager', 'manager'), ('staff', 'staff'), ('owner', 'owner'), ('resident', 'resident'), ('board_member', 'board_member'), ('customer', 'customer')], default='resident', max_length=20),
        ),
    ]
