# Generated by Django 4.2.7 on 2025-10-16 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام مجتمع')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد مجتمع')),
                ('type', models.CharField(choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('office', 'اداری'), ('mixed', 'ترکیبی')], max_length=20, verbose_name='نوع مجتمع')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('total_units', models.IntegerField(verbose_name='تعداد کل واحدها')),
                ('total_buildings', models.IntegerField(default=1, verbose_name='تعداد ساختمان\u200cها')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('board_members', models.ManyToManyField(limit_choices_to={'user_type__in': ['manager', 'board_member']}, related_name='managed_complexes', to=settings.AUTH_USER_MODEL, verbose_name='اعضای هیئت مدیره')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_complexes', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
            ],
            options={
                'verbose_name': 'مجتمع',
                'verbose_name_plural': 'مجتمع\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ساختمان')),
                ('number', models.CharField(max_length=10, verbose_name='شماره ساختمان')),
                ('floors', models.IntegerField(verbose_name='تعداد طبقات')),
                ('units_per_floor', models.IntegerField(verbose_name='واحد در هر طبقه')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='complexes.complex', verbose_name='مجتمع')),
            ],
            options={
                'verbose_name': 'ساختمان',
                'verbose_name_plural': 'ساختمان\u200cها',
                'unique_together': {('complex', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=20, verbose_name='شماره واحد')),
                ('floor', models.IntegerField(verbose_name='طبقه')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='متراژ')),
                ('status', models.CharField(choices=[('occupied', 'ساکن دارد'), ('vacant', 'خالی'), ('under_construction', 'در دست ساخت'), ('reserved', 'رزرو شده')], default='vacant', max_length=20, verbose_name='وضعیت')),
                ('rooms', models.IntegerField(default=1, verbose_name='تعداد اتاق')),
                ('parking', models.BooleanField(default=False, verbose_name='پارکینگ')),
                ('storage', models.BooleanField(default=False, verbose_name='انباری')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='complexes.building', verbose_name='ساختمان')),
                ('current_resident', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['resident', 'owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residing_units', to=settings.AUTH_USER_MODEL, verbose_name='ساکن فعلی')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['owner', 'resident']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_units', to=settings.AUTH_USER_MODEL, verbose_name='مالک')),
            ],
            options={
                'verbose_name': 'واحد',
                'verbose_name_plural': 'واحدها',
                'ordering': ['building', 'floor', 'unit_number'],
                'unique_together': {('building', 'unit_number')},
            },
        ),
    ]
