# Generated by Django 5.2.7 on 2025-10-17 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='code')),
                ('type', models.CharField(choices=[('residential', 'residential'), ('commercial', 'commercial'), ('office', 'office'), ('mixed', 'mixed')], max_length=20, verbose_name='type')),
                ('address', models.TextField(verbose_name='address')),
                ('total_floors', models.IntegerField(verbose_name='total floors')),
                ('total_units', models.IntegerField(verbose_name='total units')),
                ('total_parkings', models.IntegerField(verbose_name='total parking')),
                ('total_warehouses', models.IntegerField(verbose_name='total warehouses')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='last update')),
                ('board_members', models.ManyToManyField(limit_choices_to={'user_type__in': ['manager', 'board_member']}, related_name='managed_complexes', to=settings.AUTH_USER_MODEL, verbose_name='board members')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_complexes', to=settings.AUTH_USER_MODEL, verbose_name='create by')),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('unit_number', models.CharField(max_length=20, verbose_name='Unit Number')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Area (m²)')),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('vacant', 'Vacant'), ('under_construction', 'Under Construction')], default='vacant', max_length=20, verbose_name='Status')),
                ('rooms', models.IntegerField(default=1, verbose_name='Number of Rooms')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='complexes.building')),
                ('owner', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['owner', 'resident']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_units', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('resident', models.ForeignKey(blank=True, limit_choices_to={'user_type__in': ['resident', 'owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residing_units', to=settings.AUTH_USER_MODEL, verbose_name='Resident')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['building', 'floor', 'unit_number'],
                'unique_together': {('building', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Parking Code')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20, verbose_name='Status')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parkings', to='complexes.building', verbose_name='Building')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parkings', to='complexes.unit', verbose_name='Assigned Unit')),
            ],
            options={
                'verbose_name': 'parking',
                'verbose_name_plural': 'parkings',
                'ordering': ['building', 'floor', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('purchase', 'Purchase and sale agreement'), ('rental', 'Rental agreement'), ('transfer', 'Transfer agreement')], max_length=20, verbose_name='contract type')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='number of contract')),
                ('title', models.CharField(max_length=200, verbose_name='title of contract')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description of contract')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('duration_months', models.PositiveIntegerField(verbose_name='duration of contract (months)')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='amount of contract')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='deposit amount')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='status')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='contract file')),
                ('first_party_signed', models.BooleanField(default=False, verbose_name='First Party Signature')),
                ('second_party_signed', models.BooleanField(default=False, verbose_name='Second Party Signature')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='signed date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('first_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_first_party', to=settings.AUTH_USER_MODEL, verbose_name='First Party')),
                ('second_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_second_party', to=settings.AUTH_USER_MODEL, verbose_name='Second Party')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='complexes.unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'contract',
                'verbose_name_plural': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnitTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('ownership', 'change of ownership'), ('residency', 'change of residency'), ('both', 'change of ownership and residency')], max_length=20, verbose_name='transfer type')),
                ('transfer_date', models.DateField(verbose_name='transfer date')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='contract number')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='contract time')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='new owner')),
                ('new_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_residencies', to=settings.AUTH_USER_MODEL, verbose_name='new resident')),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='last owner')),
                ('previous_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_residencies', to=settings.AUTH_USER_MODEL, verbose_name='last resident')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='complexes.unit', verbose_name='unit')),
            ],
            options={
                'verbose_name': 'unit transfer history',
                'verbose_name_plural': 'unit transfer histories',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('floor', models.IntegerField(verbose_name='Floor')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Warehouse Code')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied')], default='available', max_length=20, verbose_name='Status')),
                ('area', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Area (m²)')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warehouses', to='complexes.building', verbose_name='Building')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warehouses', to='complexes.unit', verbose_name='Assigned Unit')),
            ],
            options={
                'verbose_name': 'warehouse',
                'verbose_name_plural': 'warehouses',
                'ordering': ['building', 'floor', 'code'],
            },
        ),
    ]
