# Generated by Django 5.2.7 on 2025-12-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True, verbose_name='key')),
                ('name', models.CharField(max_length=200, verbose_name='display name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'feature',
                'verbose_name_plural': 'features',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='buildings', to='complexes.feature', verbose_name='features'),
        ),
    ]
