# Generated by Django 4.2.7 on 2025-10-17 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complexes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitTransferHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('ownership', 'تغییر مالکیت'), ('residency', 'تغییر سکونت'), ('both', 'تغییر مالکیت و سکونت')], max_length=20, verbose_name='نوع انتقال')),
                ('transfer_date', models.DateField(verbose_name='تاریخ انتقال')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('contract_date', models.DateField(blank=True, null=True, verbose_name='تاریخ قرارداد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='مالک جدید')),
                ('new_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_residencies', to=settings.AUTH_USER_MODEL, verbose_name='ساکن جدید')),
                ('previous_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_ownerships', to=settings.AUTH_USER_MODEL, verbose_name='مالک قبلی')),
                ('previous_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_residencies', to=settings.AUTH_USER_MODEL, verbose_name='ساکن قبلی')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ثبت کننده')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='complexes.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'تاریخچه انتقال واحد',
                'verbose_name_plural': 'تاریخچه انتقالات واحدها',
                'ordering': ['-transfer_date', '-created_at'],
            },
        ),
    ]
