# Generated by Django 4.2.7 on 2025-10-17 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complexes', '0002_unittransferhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('purchase', 'قرارداد خرید و فروش'), ('rental', 'قرارداد اجاره'), ('transfer', 'قرارداد انتقال'), ('other', 'سایر قراردادها')], max_length=20, verbose_name='نوع قرارداد')),
                ('contract_number', models.CharField(max_length=100, unique=True, verbose_name='شماره قرارداد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان قرارداد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='شرح قرارداد')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('duration_months', models.PositiveIntegerField(verbose_name='مدت قرارداد (ماه)')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ قرارداد')),
                ('deposit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ ودیعه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('active', 'فعال'), ('expired', 'منقضی شده'), ('cancelled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/', verbose_name='فایل قرارداد')),
                ('first_party_signed', models.BooleanField(default=False, verbose_name='امضای طرف اول')),
                ('second_party_signed', models.BooleanField(default=False, verbose_name='امضای طرف دوم')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='تاریخ امضا')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('first_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_first_party', to=settings.AUTH_USER_MODEL, verbose_name='طرف اول')),
                ('second_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_second_party', to=settings.AUTH_USER_MODEL, verbose_name='طرف دوم')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='complexes.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-created_at'],
            },
        ),
    ]
