# Generated by Django 4.2.7 on 2025-10-17 16:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('complexes', '0003_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_type', models.CharField(choices=[('storage', 'انباری'), ('parking', 'پارکینگ'), ('warehouse', 'انبار بزرگ'), ('other', 'سایر')], max_length=20, verbose_name='نوع فضای ذخیره\u200cسازی')),
                ('unit_number', models.CharField(max_length=20, verbose_name='شماره انباری/پارکینگ')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('location', models.CharField(max_length=200, verbose_name='موقعیت')),
                ('area', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='متراژ (متر مربع)')),
                ('capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='ظرفیت')),
                ('features', models.TextField(blank=True, null=True, verbose_name='ویژگی\u200cها')),
                ('is_covered', models.BooleanField(default=False, verbose_name='سرپوشیده')),
                ('has_electricity', models.BooleanField(default=False, verbose_name='دارای برق')),
                ('has_lighting', models.BooleanField(default=True, verbose_name='دارای روشنایی')),
                ('status', models.CharField(choices=[('available', 'خالی'), ('occupied', 'اشغال شده'), ('reserved', 'رزرو شده'), ('maintenance', 'در دست تعمیر')], default='available', max_length=20, verbose_name='وضعیت')),
                ('monthly_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ماهیانه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_storages', to='complexes.unit', verbose_name='واحد مرتبط')),
                ('complex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_units', to='complexes.complex', verbose_name='مجتمع')),
            ],
            options={
                'verbose_name': 'انباری/پارکینگ',
                'verbose_name_plural': 'انباری\u200cها و پارکینگ\u200cها',
                'ordering': ['complex', 'storage_type', 'unit_number'],
                'unique_together': {('complex', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='StorageMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('maintenance_type', models.CharField(choices=[('cleaning', 'نظافت'), ('repair', 'تعمیرات'), ('inspection', 'بازرسی'), ('painting', 'رنگ\u200cآمیزی'), ('other', 'سایر')], max_length=20, verbose_name='نوع نگهداری')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=20, verbose_name='اولویت')),
                ('scheduled_date', models.DateField(verbose_name='تاریخ برنامه\u200cریزی شده')),
                ('estimated_duration', models.PositiveIntegerField(verbose_name='مدت تخمینی (ساعت)')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع واقعی')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان واقعی')),
                ('status', models.CharField(choices=[('available', 'خالی'), ('occupied', 'اشغال شده'), ('reserved', 'رزرو شده'), ('maintenance', 'در دست تعمیر')], default='available', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='مسئول')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_maintenances', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='complexes.storageunit', verbose_name='انباری/پارکینگ')),
            ],
            options={
                'verbose_name': 'نگهداری انباری/پارکینگ',
                'verbose_name_plural': 'نگهداری انباری\u200cها و پارکینگ\u200cها',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='StorageAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_type', models.CharField(choices=[('ownership', 'مالکیت'), ('rental', 'اجاره'), ('temporary', 'موقت'), ('shared', 'اشتراکی')], max_length=20, verbose_name='نوع تخصیص')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('monthly_fee', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='هزینه ماهیانه')),
                ('is_included_in_charge', models.BooleanField(default=True, verbose_name='شامل در شارژ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('contract_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره قرارداد')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('storage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='complexes.storageunit', verbose_name='انباری/پارکینگ')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_assignments', to='complexes.unit', verbose_name='واحد')),
            ],
            options={
                'verbose_name': 'تخصیص انباری/پارکینگ',
                'verbose_name_plural': 'تخصیص\u200cهای انباری و پارکینگ',
                'ordering': ['-start_date'],
            },
        ),
    ]
